name: CD - unxt

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "src/**"
      - "pyproject.toml"
      - "README.md"
      - ".github/workflows/cd-unxt.yml"
  push:
    branches:
      - main
    tags:
      - "unxt-v*"
    paths:
      - "src/**"
      - "pyproject.toml"
      - "README.md"
      - ".github/workflows/cd-unxt.yml"
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3

jobs:
  build:
    name: Build & inspect package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      attestations: write

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.5.0
        with:
          # Required for hatch-vcs to determine version from git tags.
          # Can be removed if switching to hardcoded versions.
          fetch-depth: 0
          persist-credentials: false

      - uses: hynek/build-and-inspect-python-package@efb823f52190ad02594531168b7a2d5790e66516 # v2.14.0
        with:
          path: .
          upload-name-suffix: -unxt
          attest-build-provenance-github:
            ${{ github.event_name != 'pull_request' }}

  publish-testpypi:
    name: Publish to TestPyPI
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/unxt
    permissions:
      id-token: write
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/unxt-v')) ||
      (github.event_name == 'release' && github.event.action == 'published')

    steps:
      - name: Download built artifact to dist/
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: Packages-unxt
          path: dist

      - uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          repository-url: https://test.pypi.org/legacy/

  publish-pypi:
    name: Publish to PyPI
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/unxt
    permissions:
      id-token: write
    if: |
      github.event_name == 'release' &&
      github.event.action == 'published' &&
      startsWith(github.event.release.tag_name, 'unxt-v')

    steps:
      - name: Download built artifact to dist/
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: Packages-unxt
          path: dist

      - uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
